#webserver tasks
- name: Installeer apache2, php, en php-mysql
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apache2
    - php
    - php-mysql
  notify: Restart apache

- name: Deploy sample site
  copy:
    dest: /var/www/html/index.html
    content: "<html>Hello IaC examinator</html>"
  notify: Restart apache

- name: Enable apache service
  service:
    name: apache2
    state: started
    enabled: true
