#webserver tasks
- name: Installeer apache2, php, en php-mysql
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apache2
    - php
    - php-mysql
  notify: Restart apache
